import { ShipmentModel } from './shipment';
import {ReferenceField} from "./reference-field.model";
export class BookingModel {

    hasError: boolean = false;
    errors: string[] = [];
    shipperBookingRefId: string;
    carrierBookingRefId: string;
    masterBOLNumber: string;
    carrierCode: string;
    currencyCode: string;
    originFacilityName: string;
    originAddress: string;
    originCity: string;
    originCounty: string;
    originStateProv: string;
    originPostalCode: string;
    originCountryCode: string;
    originShipvia: string;
    originShipviaBU: number;
	originFacilityBUId: number;
    originFacilityId: string;
    destFacilityName: string;
    destFacilityId: string;
    destFacilityBUId: number;
    destAddress: string;
    destCity: string;
    destCounty: string;
    destStateProv: string;
    destPostalCode: string;
    destCountryCode: string;
    destShipvia: string;
    destShipviaBU: number;
    accessorialCosts: number;
    invoiceBusinessUnit: string;
    invoiceBusinessUnitInt: number;
    carrierBU: string;
    carrierBUInt: number;
    shipments: ShipmentModel[] =[];
    invoiceNumber: string;
    invoiceDate: string;
    paymentDueDate: string;
    receivedDate: string;
    selectedCosts: string[];
    invoiceTotalString: string;
    bookingType: string;
    incotermCode: string;
    vesselName: string;
    mode: string;
    shipDate: string;
    voyageFlightNumber: string;
    secondaryCarrier: string;
    secondaryCarrierBUName: string;
    billingMethod: string;
    invoiceId:number;
    paymentTerms: number;
    referenceField: ReferenceField[];
    constructor(obj: any) {
        this.hasError = obj.hasError;
        this.errors = obj.errors;
        this.shipperBookingRefId = obj.shipperBookingRefId;
        this.carrierBookingRefId = obj.carrierBookingRefId;
        this.masterBOLNumber = obj.masterBOLNumber;
        this.currencyCode = obj.currencyCode;
        this.originFacilityName = obj.originFacilityName;
        this.originAddress = obj.originAddress;
        this.originCity = obj.originCity;
        this.originCounty = obj.originCounty;
        this.originStateProv = obj.originStateProv;
        this.originPostalCode = obj.originPostalCode;
        this.originCountryCode = obj.originCountryCode;
        this.originFacilityBUId = obj.originFacilityBUId;
        this.originFacilityId = obj.originFacilityId;
        this.destFacilityName = obj.destFacilityName;
        this.destAddress = obj.destAddress;
        this.destCity = obj.destCity;
        this.destCounty = obj.destCounty;
        this.destStateProv = obj.destStateProv;
        this.destPostalCode = obj.destPostalCode;
        this.destCountryCode = obj.destCountryCode;
        this.destFacilityId = obj.destFacilityId;
        this.destFacilityBUId = obj.destFacilityBUId;
        this.accessorialCosts = obj.accessorialCosts;
        this.carrierCode = obj.carrierCode;
        this.invoiceBusinessUnit = obj.invoiceBusinessUnit;
        this.invoiceBusinessUnitInt = obj.invoiceBusinessUnitInt;
        this.carrierBU = obj.carrierBU;
        this.carrierBUInt = obj.carrierBUInt;
        this.shipments = obj.shipments;
        this.invoiceNumber = obj.invoiceNumber;
        this.invoiceDate = obj.invoiceDate;
        this.paymentDueDate = obj.paymentDueDate;
        this.receivedDate = obj.receivedDate;
        this.invoiceTotalString = obj.invoiceTotalString;
        this.originShipvia = obj.originShipvia;
        this.originShipviaBU = obj.originShipviaBU;
        this.destShipvia = obj.destShipvia;
        this.destShipviaBU = obj.destShipviaBU;
        this.bookingType = obj.bookingType;
        this.incotermCode = obj.incotermCode;
        this.vesselName = obj.vesselName;
        this.mode = obj.mode;
        this.shipDate = obj.shipDate;
        this.voyageFlightNumber = obj.voyageFlightNumber;
        this.secondaryCarrier = obj.secondaryCarrier;
        this.billingMethod = obj.billingMethod;
        this.referenceField = obj.referenceField;
        this.invoiceId = obj.invoiceId;
        this.selectedCosts = obj.selectedCosts || [];
        this.paymentTerms = obj.paymentTerms;
        this.secondaryCarrierBUName = obj.secondaryCarrierBUName;
    }
}